title:            Panic
description: >
    start my way
url:              # Site url.
signoff:          # Your name.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Email
    url:          mailto:domobhaoran@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/huhr
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
