title:            Panic
description: >
    好像写写技术blog，看起来会比较高大上的样子
url:              # Site url.
signoff:          # Your name.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Email
    url:          mailto:huhaoran@domob.cn
    external:     true
  - name:         GitHub
    url:          http://github.com/huhr
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
