# Site settings
title: Panic
email: huhaoran@domob.cn
description: > # this means to ignore newlines until "baseurl:"
    好像写写技术blog，看起来会比较高大上的样子
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  huhr

# Build settings
markdown: kramdown
